### ISSUE TITLE
Crashes on 1.15.2 when breaking a locked chest

### ISSUE THREAD

**Issue by serpi90** [Boundarybreaker/Locky#6]
Either on single player or server:
1. Place a chest, save some stuff inside.
2. Lock it
3. Break it with or without the lock
4. Crash

```plaintext
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2/19/20 1:17 AM
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access method net.minecraft.class_2519.<init>(Ljava/lang/String;)V from class net.minecraft.class_2248
	at net.minecraft.class_2248.handler$zbh000$dropOnBreak(class_2248.java:1168)
	at net.minecraft.class_2248.method_9576(class_2248.java)
	at net.minecraft.class_3225.method_14266(class_3225.java:243)
	at net.minecraft.class_3225.method_21717(class_3225.java:217)
	at net.minecraft.class_3225.method_14263(class_3225.java:146)
	at net.minecraft.class_3244.method_12066(class_3244.java:912)
	at net.minecraft.class_2846.method_12361(class_2846.java:40)
	at net.minecraft.class_2846.method_11054(class_2846.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:138)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:725)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:719)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 5.4.18-1-MANJARO
	Java Version: 1.8.0_242, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4008508088 bytes (3822 MB) / 5127536640 bytes (4890 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xms2048m -Xmx8192m
	Fabric Mods: 
		fabric: Fabric API 0.4.32+build.292-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.6+build.180
		locky: Locky 1.2.1+1.14.3
		minecraft: Minecraft 1.15.2
	Player Count: 1 / 8; [class_3222['serpi90'/245, l='New World', x=-9.67, y=4.00, z=93.32]]
	Data Packs: vanilla, fabric/fabric-mining-levels-v0 (incompatible), fabric/locky (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'```

**Comment by LemmaEOF** [comment]
oh boy, did they screw up the stuff Locky uses for this, wonderful

I'll take a look when I have time

**Comment by serpi90** [comment]
Thank you, i tried to look at it, but my java experience is very limited.

**Comment by LemmaEOF** [comment]
oh I know what this is! They changed the way you create new tags. This is an easy fix.
